-- Table: Users
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL, -- Stores hashed password
    role VARCHAR2(50) NOT NULL
);

-- Table: Tables
CREATE TABLE tables (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    capacity NUMBER(3) NOT NULL,
    status VARCHAR2(20) NOT NULL
);

-- Table: Reservations
CREATE TABLE reservations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    table_id NUMBER NOT NULL,
    reservation_datetime TIMESTAMP NOT NULL,
    status VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_reservations_user FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_reservations_table FOREIGN KEY (table_id) REFERENCES tables(id)
        ON DELETE CASCADE
);



